# SPDX-FileCopyrightText: The WinLinTDPControl Developers
#
# SPDX-License-Identifier: Apache-2.0

[workspace]
members = [
    "src/kernel/linux",
    "src/kernel/windows",
    "src/common"
]
resolver = "1"
