# SPDX-FileCopyrightText: The PwrCtrl Developers
#
# SPDX-License-Identifier: Apache-2.0

[package]
authors.workspace = true
categories.workspace = true
description = "Windows kernel driver for PwrCtrl"
homepage.workspace = true
keywords.workspace = true
license.workspace = true
name = "pwrctrl-windows"
readme.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
pwrctrl-common = { path = "../../../lib/common" }

[target.'cfg(target_os = "windows")'.build-dependencies]
kernel-build = "0.1.0"
