# SPDX-FileCopyrightText: The WinLinTDPControl Developers
#
# SPDX-License-Identifier: MIT

[package]
name = "winlintdpcontrol-windows"
version = "0.1.0"
edition = "2021"

[dependencies]

[build-dependencies]
kernel-build = "0.1.0"
