# SPDX-FileCopyrightText: The WinLinTDPControl Developers
#
# SPDX-License-Identifier: Apache-2.0

[package]
name = "winlintdpcontrol-linux"
version = "0.1.0"
edition = "2021"

[dependencies]
winlintdpcontrol-common = { path = "../../common" }
