# SPDX-FileCopyrightText: The WinLinTDPControl Developers
#
# SPDX-License-Identifier: Apache-2.0

[package]
authors.workspace = true
description = "Linux kernel driver for WinLinTDPControl"
edition.workspace = true
homepage.workspace = true
license.workspace = true
name = "winlintdpcontrol-linux"
readme.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
winlintdpcontrol-common = { path = "../../../lib/common" }
