[package]
authors.workspace = true
categories.workspace = true
description = "Stub program for PwrCtrl"
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
name = "stub"
readme.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
