# SPDX-FileCopyrightText: The WinLinTDPControl Developers
#
# SPDX-License-Identifier: Apache-2.0

[package]
name = "winlintdpcontrol-common"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.75", default-features = false }
thiserror-no-std = "2.0.2"
